FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY driver-location-service/pom.xml ./driver-location-service/
RUN mvn dependency:go-offline -pl driver-location-service -am -q
COPY driver-location-service/src ./driver-location-service/src
RUN mvn clean package -DskipTests -pl driver-location-service -am -q

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/driver-location-service/target/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
